name: 'helm'

on:
  workflow_dispatch:
    inputs:
      version:
      descritpion: 'The local-path-provisioner'
      required: true
  schedule:
    - cron: '0 0 * * *'

jobs:
  # The "build" workflow
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout local-path-provisioner
      uses: actions/checkout@v2
      with:
        repository: rancher/local-path-provisioner
    - name: Checkout to right branch/tag
      run: |
        if [ ${{ github.event.inputs.version }} != ""]; then
          git checkout ${{ github.event.inputs.version }}
        fi
    - name: Fix path name
      run: |
        mkdir charts
        mv deploy/chart charts/local-path-provisioner
    - uses: goodsmileduck/helm-push-action@v3.3.1
      env:
        SOURCE_DIR: 'charts'
        CHART_FOLDER: 'local-path-provisioner'
        FORCE: 'True'
        CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}